version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: coco
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://coco:password@db:5432/test
    ports:
      - "8080:8080"
    volumes:
      - .:/app
