version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: coco
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://coco:password@db:5432/test
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  redis:
    image: redis:latest
    container_name: redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A celery_app worker --loglevel=info
    depends_on:
      - redis
      - app
    environment:
      DATABASE_URL: postgresql://coco:password@db:5432/test
    volumes:
      - .:/app

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_beat
    command: celery -A celery_app beat --loglevel=info --schedule=/var/run/celerybeat-schedule
    depends_on:
      - redis
      - app
    environment:
      DATABASE_URL: postgresql://coco:password@db:5432/test
    volumes:
      - .:/app
      - /var/run/celery:/var/run/celery

volumes:
  db_data:
