# Utiliser l'image officielle de Python
FROM python:3.9-slim

# Installer les dépendances système
RUN apt-get update && apt-get install -y \
    libpq-dev \
    && apt-get clean

# Copier les fichiers de l'application
COPY . /app
WORKDIR /app

# Installer les dépendances Python
RUN pip install --no-cache-dir -r requirements.txt

# Commande d'entrée par défaut
CMD ["python", "postgres.py"]
