name: Build and Deploy FastAPI Service
on:
  push:
    branches:
      - main

env:
  PROJECT_ID: iaas-tp1-421811
  GAR_LOCATION: europe-west9
  REPOSITORY: iaas-tp1-register
  SERVICE: youtube-api-job-service
  REGION: europe-west9  

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}' 
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'

      - name: Build FastAPI Service
        run: docker-compose -f docker-compose.prod.yml build app

      - name: Tag and Push FastAPI Service
        run: |
          IMAGE_ID=$(docker-compose -f docker-compose.prod.yml images -q app)
          echo "FastAPI Service Image ID: $IMAGE_ID"
          docker tag $IMAGE_ID "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"

      - name: Deploy FastAPI Service to Cloud Run
        id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}
          env_vars: |
            DATABASE_URL=projects/${{ secrets.GCP_PROJECT }}/secrets/DATABASE_URL/versions/latest
