name: Build and Deploy to Cloud Run
on:
  push:
    branches:
      - main

env:
  PROJECT_ID: iaas-tp1-421811
  GAR_LOCATION: europe-west9
  REPOSITORY: iaas-tp1-register
  FASTAPI_SERVICE: youtube-api-job-service
  POSTGRES_JOB_SERVICE: postgres-job-service
  REGION: europe-west9  

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}' 
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'

      - name: Build and Push FastAPI Service
        run: |-
          docker-compose -f docker-compose.prod.yml build app
          docker tag $(docker-compose -f docker-compose.prod.yml images -q app) "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.FASTAPI_SERVICE }}:${{ github.sha }}"
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.FASTAPI_SERVICE }}:${{ github.sha }}"

      - name: Build and Push PostgreSQL Job
        run: |-
          docker-compose -f docker-compose.prod.yml build job
          docker tag $(docker-compose -f docker-compose.prod.yml images -q job) "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.POSTGRES_JOB_SERVICE }}:${{ github.sha }}"
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.POSTGRES_JOB_SERVICE }}:${{ github.sha }}"

      - name: Deploy FastAPI Service to Cloud Run
        id: deploy_fastapi
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ env.FASTAPI_SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.FASTAPI_SERVICE }}:${{ github.sha }}
          env_vars: |
            DATABASE_URL=projects/${{ secrets.GCP_PROJECT }}/secrets/DATABASE_URL/versions/latest

      - name: Deploy PostgreSQL Job to Cloud Run
        id: deploy_postgres_job
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ env.POSTGRES_JOB_SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.POSTGRES_JOB_SERVICE }}:${{ github.sha }}
          env_vars: |
            DATABASE_URL=projects/${{ secrets.GCP_PROJECT }}/secrets/DATABASE_URL/versions/latest
